version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:1.8
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"

  proxy:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - "80:8080"
      #- "443:8443"
      - "443:8443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./server-confs:/server-confs:ro
    environment:
      - AUTO_LETS_ENCRYPT=no
      - REDIRECT_HTTP_TO_HTTPS=no
      - USE_REVERSE_PROXY=yes
      - SERVER_NAME=qian.istic.univ-rennes1.fr qian.pad.diverse-team.fr
      - MULTISITE=yes
      - PROXY_REAL_IP=yes

  back:
    image: end_tlc
    restart: always
    environment:
      - doodle.internalPadUrl=http://etherpad:9001
      - doodle.externalPadUrl=http://qian.pad.diverse-team.fr/

  front:
    image: front_tlc


